-- MySQL Script generated by MySQL Workbench
-- Thu Nov  3 10:46:00 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema VideoGames
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema VideoGames
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `VideoGames` DEFAULT CHARACTER SET utf8 ;
USE `VideoGames` ;

-- -----------------------------------------------------
-- Table `VideoGames`.`Genre`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `VideoGames`.`Genre` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `genre_type` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `VideoGames`.`Game`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `VideoGames`.`Game` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `game_name` VARCHAR(45) NULL,
  `Genre_id` INT NOT NULL,
  PRIMARY KEY (`id`, `Genre_id`),
  INDEX `fk_Game_Genre1_idx` (`Genre_id` ASC) VISIBLE,
  CONSTRAINT `fk_Game_Genre1`
    FOREIGN KEY (`Genre_id`)
    REFERENCES `VideoGames`.`Genre` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `VideoGames`.`Player`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `VideoGames`.`Player` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `player_name` VARCHAR(45) NULL,
  `player_age` INT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `VideoGames`.`Platform`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `VideoGames`.`Platform` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `platform_name` VARCHAR(45) NULL,
  `Player_id` INT NOT NULL,
  PRIMARY KEY (`id`, `Player_id`),
  INDEX `fk_Platform_Player1_idx` (`Player_id` ASC) VISIBLE,
  CONSTRAINT `fk_Platform_Player1`
    FOREIGN KEY (`Player_id`)
    REFERENCES `VideoGames`.`Player` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `VideoGames`.`Game_has_Platform`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `VideoGames`.`Game_has_Platform` (
  `Game_id` INT NOT NULL,
  `Platform_id` INT NOT NULL,
  PRIMARY KEY (`Game_id`, `Platform_id`),
  INDEX `fk_Game_has_Platform_Platform1_idx` (`Platform_id` ASC) VISIBLE,
  INDEX `fk_Game_has_Platform_Game_idx` (`Game_id` ASC) VISIBLE,
  CONSTRAINT `fk_Game_has_Platform_Game`
    FOREIGN KEY (`Game_id`)
    REFERENCES `VideoGames`.`Game` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Game_has_Platform_Platform1`
    FOREIGN KEY (`Platform_id`)
    REFERENCES `VideoGames`.`Platform` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `VideoGames`.`Game_has_Player`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `VideoGames`.`Game_has_Player` (
  `Game_id` INT NOT NULL,
  `Player_id` INT NOT NULL,
  PRIMARY KEY (`Game_id`, `Player_id`),
  INDEX `fk_Game_has_Player_Player1_idx` (`Player_id` ASC) VISIBLE,
  INDEX `fk_Game_has_Player_Game1_idx` (`Game_id` ASC) VISIBLE,
  CONSTRAINT `fk_Game_has_Player_Game1`
    FOREIGN KEY (`Game_id`)
    REFERENCES `VideoGames`.`Game` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Game_has_Player_Player1`
    FOREIGN KEY (`Player_id`)
    REFERENCES `VideoGames`.`Player` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

use videogames;

insert into genre (id, genre_type)
values 
(1, "Stealth"),
(2, "Action"),
(3, "Horror"),
(4, "Racing"),
(5, "Adventure")
(6, "Strategy");


insert into player (player_name, player_age)
values 
("Filippos" , 32),
("Daniel" , 32),
("Attila" , 35),
("Erik" , 36),
("Helder" , 19);


insert into game (game_name, Genre_id)
values 
("Metal Gear Solid", 1),
("Resident Evil", 3),
("Silent Hill", 3),
("GTA", 2),
("Gran Turismo", 4),
("Need For Speed", 4),
("Dirt", 4);


insert into platform (platform_name, player_id)
values ("XBOX", 1), ("XBOX", 2) , ("Playstation" ,3),("Playstation" ,4),("Playstation" ,5);